#!/bin/bash
#Execution script for a quick file comparison
	#.out files generated by teacher
	#.res files generated by executar.sh
a=0
for i in $(ls *.out);
do
	#Compares both files
	diff $i arq$a.res
	b="$?"
	echo "$b"
	#Breaks if there are any errors
	if [ "$b" != "0" ];
	then
		break
	fi
	let a=a+1
done
