#!/bin/bash
#Execution script for .res file generation from .c code
	#.in files generated by teacher
	#Running Valgrind for memory leak checking
a=0
#Here you set your program's name
b="bits"
for i in $(ls *.in);
do
	valgrind ./$b <$i >arq$a.res
	#If there are any errors, it breaks
	if [ "$?" != "0" ];
	then
		break
	fi
	let a=a+1
done

